### ISSUE TITLE
Add Statusbar functions

### ISSUE THREAD

**Issue by AlexanderSchorn** [DifferentLink/Grape#108]

**Comment by AlexanderSchorn** [comment]
Specification of the statusbar:
1.) Pause/continue calculation (done)
2.) Show amount of uncalculated graphs
3.) Indicate graph position in GUI table (Robin)
4.) Indicate amount of graphs that are in the GUI table
5.) Show log entries (done)

**Comment by DifferentLink** [comment]
The necessary functions are now available in StatusbarUI
