### ISSUE TITLE
password field should be a password field

### ISSUE THREAD

**Issue by LeanderK** [DifferentLink/Grape#250]
When configuring Databases the password field ist not hiding the password.
![image](https://user-images.githubusercontent.com/2179853/36978978-5a3966de-2086-11e8-8029-a8b9913cb47b.jpeg)

**Comment by grecht** [comment]
@DifferentLink exactly what we talked about a couple weeks ago :grin:

**Comment by LeanderK** [comment]
Currently, the input of multiple lines is allowed. Does this make sense?

**Comment by LeanderK** [comment]
I can't assign bug-labels to my issues, so somebody from the team should do it.

**Comment by grecht** [comment]
Reopened issue because input of multiple lines does not make sense at all.

**Comment by koehlerfelix** [comment]
Closed issue because input of multiple lines is not possible
