### ISSUE TITLE
Database Exception gets swallowed

### ISSUE THREAD

**Issue by LeanderK** [DifferentLink/Grape#253]
When I try to connect with an non-existing db/using an incorrect password, I don't get an error-message.

**Comment by CemOezcan** [comment]
The error-message is displayed at the log section, you have to press the log-button to see it.

**Comment by LeanderK** [comment]
I think you would agree that this is not obvious and that a proper error message would be appropriate. I have followed the software quite closely and didn't think of the log, I don't image a user not as familiar with the software would look in there.
