### ISSUE TITLE
Navigating the Resultset is lagging

### ISSUE THREAD

**Issue by LeanderK** [DifferentLink/Grape#256]
When navigating the resultset using the keyboard, the application quickly becomes unresponsive and only recovers later.

**Comment by grecht** [comment]
How big was the resultset? My machine navigates a database of ~80 graphs smoothly.

**Comment by DifferentLink** [comment]
I can't reproduce this either. Navigating a database with almost 200 graphs works smoothly for me.

**Comment by grecht** [comment]
@DifferentLink Maybe this is an OS-specific problem once again... :grin:

**Comment by LeanderK** [comment]
I would put this issue on hold for our weekly meeting.

**Comment by grecht** [comment]
Closed as issue could not be reproduced on Linux/Windows
