### ISSUE TITLE
Valid Filters

### ISSUE THREAD

**Issue by LeanderK** [DifferentLink/Grape#257]
What are all the valid expression in the filter-menu?

**Comment by uuiqo** [comment]
Currently we support tree schemata of expressions:
1) Basic filter: Basic filter always have the form <Property> <Relation> <Number>
2) Complex filter: Complex filter always have the form <Property> <Operator> <Number> <Relation> <Property> <Operator> <Number>
3) To check the HadwigerConjecture / TotalColoringConjecture just enter <HadwigerConjecture> or <TotalColoringConjecture>
Note: <Relation> stays for =, < , > <= or >=
<Operator> stays for +, -, *, /
<Number> stays for an interger or a double value

**Comment by LeanderK** [comment]
which complex filters are all supported?

**Comment by koehlerfelix** [comment]
All combinations with properties that are represented by an integer or a double value.
Additionally $Number$ has to be a positive integer or double

**Comment by uuiqo** [comment]
There are tree forms of complex filters that are accepted:
1)  $Property$ $Operator$ $Number$ $Relation$ $Property$ $Operator$ $Number$
2)  $Property$ $Relation$ $Property$ $Operator$ $Number$
3)  $Property$ $Operator$ $Number$ $Relation$ $Property$

**Comment by LeanderK** [comment]
Thanks!
