### ISSUE TITLE
correct log entries

### ISSUE THREAD

**Issue by koehlerfelix** [DifferentLink/Grape#262]
entry:
if graph is already in the database (f.e if you click the button nextDenser but the next denser graph is already in the database)

for graph generating: f.e 42 graphs were generated. 100 different graphs not found. -> if the input says 100 graphs

logentries are created twice sometimes

**Comment by koehlerfelix** [comment]
if something goes wrong with the generation of a graph via bfs code because the regex checks only simple cases and not if f.e the graph is connected -> exception can appear

**Comment by grecht** [comment]
after deleting graphs via right-click menu, no log entry is shown

**Comment by grecht** [comment]
lots of exceptions are still swallowed and are not displayed in the log

**Comment by koehlerfelix** [comment]
I think its better to make a log message for the user instead of throwing an exception in the controller package

**Comment by koehlerfelix** [comment]
Suggestions:
-database "NAME" opened
-deleted graph "ID"
-generated "NUMBER" graphs
-added bfs graph
-added drew graph
-saved database "NAME"
...

**Comment by koehlerfelix** [comment]
log messages are behind log events (BUG)
