### ISSUE TITLE
Dropdownmenu contains Properties that are not allowed in the filter input

### ISSUE THREAD

**Issue by koehlerfelix** [DifferentLink/Grape#264]
f.e BfsCode

**Comment by DifferentLink** [comment]
The suggested properties come from the PropertyFactory for PropertyGraphs. The GUI shouldn't know which properties make valid expressions.

**Comment by grecht** [comment]
@DifferentLink that's right. I could add an createFilterableProperties() method to PropertyFactory. @uuiqo will have to adjust how he gets the filterable properties in his filter package.

**Comment by DifferentLink** [comment]
Works for me
