### ISSUE TITLE
Filter in filtergroups disappears when restarting the programm

### ISSUE THREAD

**Issue by koehlerfelix** [DifferentLink/Grape#284]
filter in filtergroups are not saved if you open a database

**Comment by CemOezcan** [comment]
Filters that belong to a filter-group are saved as SimpleFilter-objects without a filter-group, meaning that
they are displayed as SimpleFilter-objects the next time the database is opened.

**Comment by koehlerfelix** [comment]
Loaded Filter from a Database were printed always as property + value = property + value
f.e create filter numberOfVertices = 2 -> load database -> numberOfVertieces + 0 = 2
