### ISSUE TITLE
main window closes after opening a database (on windows)

### ISSUE THREAD

**Issue by koehlerfelix** [DifferentLink/Grape#286]

**Comment by koehlerfelix** [comment]
main window appears behind intelliJ after pressing  configure

**Comment by koehlerfelix** [comment]
same behavior by pressing the close button on the top right corner

**Comment by koehlerfelix** [comment]
if you deactivate the dispose methd in ConfigureDatabaseAction, on the one hand the database creation window does not close but grape don't move in the background (that's strange)

**Comment by DifferentLink** [comment]
Please test whether this, or something similar, still happens if you start Grape from an executable .jar
