### ISSUE TITLE
Grapheditor frame can be made too small to see all the graph's vertices

### ISSUE THREAD

**Issue by grecht** [DifferentLink/Grape#309]
![screenshot from 2018-03-09 07-43-35](https://user-images.githubusercontent.com/8888574/37194597-4a8e80a2-236f-11e8-9281-82f73820f04f.png)
-> limit smallest size of filter & grapheditor frame

**Comment by koehlerfelix** [comment]
with the pullrequest the graph is always completely shown by clicking the center button
