### ISSUE TITLE
Textfield of the correlation does only change its background color if the button gets pressed

### ISSUE THREAD

**Issue by koehlerfelix** [DifferentLink/Grape#315]
i think its better if the background color is f.e white as soon as the input as valid like the at filter textfield

**Comment by koehlerfelix** [comment]
Maybe a suggestion at the correlation textfile like the suggestions at the filter textfile is usefull to

**Comment by DifferentLink** [comment]
The branch gui/correlation-improvements has (outcommented) functionality to do this. But checking is slow if the input turns valid.
@uuiqo should maybe provide a method that allows the gui to quickly check the validity of an input
The interesting method where the gui does the check can be found here: CorrelationUI#CorrelationInputChangeListener#update()
