### ISSUE TITLE
Toggling filtergroups doesn't update table

### ISSUE THREAD

**Issue by DifferentLink** [DifferentLink/Grape#322]

**Comment by koehlerfelix** [comment]
Always returns the table with all available graphs.

**Comment by DifferentLink** [comment]
@uuiqo can you have a look at this?
You want to check FilterUI#ToggleFilterGroupAction#actionPerformed. I suspect that the filters aren't updatet properly in the filter package.

**Comment by grecht** [comment]
The FilterGroup itself is probably updated, but not its filters.
