### ISSUE TITLE
save all relevant properties in database

### ISSUE THREAD

**Issue by uuiqo** [DifferentLink/Grape#62]
the following properties need to be saved in database but are not saved yet:
- [does the graph fulfill the HadwigerConjecture / TotalColoringConjecture]
- size of largest clique in graph
- number of unnecessary nodes for creation of subgraphs
- size of largest subgraph (HadwigerConjecture)

**Comment by grecht** [comment]
Hadwiger conjecture and total coloring conjecture were not supposed to be properties, but filters as they are based on several other properties.
